version: "3.9"

services:
  devopsdb: 
    image: sandeepmudipampula/newrepo:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    image: sandeepmudipampula/newrepo:javaapp
    ports:
      - "1119:8080"
    deploy:
      replicas: 1
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
